name = "fqnovel-api"
main = "build/worker/shim.mjs"
compatibility_date = "2024-09-06"

[vars]
# 这里只留不敏感的固定配置，或者全删掉去后台配
aid = "1967"
update_version_code = "62532"

[build]
command = "cargo install -q worker-build && worker-build --release"
